Bw assurance research path page add.
nhsengland/datascience pull request #150
Opened 2024-12-30 10:18 UTC by benwallace2nhs

# Description

❓**What**:

🧠**Why?**:

👨‍💻**How?**:

# Checklist:
Have checked for the following:
- [ x] The website still builds correctly, and you can view it using `mkdocs serve`.
- [ x] There are no new "warnings" from mkdocs
- [ x] Does your page follow the [page template](https://nhsdigital.github.io/rap-community-of-practice/example_RAP_CoP_page/) (or [here in Markdown](https://github.com/NHSDigital/rap-community-of-practice/blob/main/docs/example_RAP_CoP_page.md))? (**need to make a new one specific to NHSE Data Science**)
- [ x] Spelling errors
- [ x] Consistent capitalization
- [ ] Consistent numbers
- [ ] Material features incorrectly implemented: search for code blocks and markers (e.g. !!!).
- [ ] Code snippets don't work
- [ ] Images not working
- [ ] Links not working

## Where it was tested

- Github Codespaces - 2-core, 4GB RAM, 32GB hard drive
- devcontainer.json describes further settings

2025-01-07 12:18 UTC, amaiaita requested changes

2025-01-07 12:18 UTC, amaiaita commented on docs/our_work/ds278_Assurance_Research_Path.md
> +tags: ['NLP','LLM','GENAI',Assurance, Machine Learning, Classification, Computer Vision, Work in Progress]
please check this page for the currently existing tags https://nhsengland.github.io/datascience/our_work/tags/ , and try and align to them, if you dont think theyre appropriate, let me know any suggestions you might have!

2025-01-07 12:18 UTC, amaiaita commented on docs/our_work/ds278_Assurance_Research_Path.md
> +title: 'DS_278: Assurance Research Path'
I wouldnt give the name of it the DS code, cause this is public facing and that doeasnt mean anything to anyone oputside the team + just clutters up the titles

2025-01-07 12:18 UTC, amaiaita commented on docs/our_work/ds278_Assurance_Research_Path.md
> +The NHS AI Quality Community of Practice (AIQ CoP) is a network of testing and assurance professionals dedicated to supporting the assurance of healthcare AI. While not an assurance function itself,
be consisrent on how you capitalise the acronym so either AIQ CoP or AIQCOP every time

2025-01-07 12:18 UTC, amaiaita commented on docs/our_work/ds278_Assurance_Research_Path.md
> +Read our Mixup Assurance paper here:  - [Link to paper](https://arxiv.org/abs/2311.13978)
```suggestion
Read our Mixup Assurance paper here [on ArXiv](https://arxiv.org/abs/2311.13978)
```

just think it looks nicer this way! might also be worth giving a very brief explanation of what Mixup is

2025-01-07 12:18 UTC, amaiaita commented on docs/our_work/ds278_Assurance_Research_Path.md
> +RISE is an experimental tool which can help assurers, data scientists and clinicians to evaluate Ai Classifiers, read more here: - [Link to blog ](https://nhsengland.github.io/datascience/articles/20
```suggestion
RISE is an experimental tool which can help assurers, data scientists and clinicians to evaluate Ai Classifiers, read more [on the blog](https://nhsengland.github.io/datascience/articles/2024/12/12/RISE_tool/)  
```

2025-01-07 12:18 UTC, amaiaita commented on docs/our_work/ds278_Assurance_Research_Path.md
> +Alternatively you can always email us at: nhsdigital.instant@nhs.net
make this a clickable email address

2025-01-07 12:18 UTC, amaiaita commented on docs/our_work/ds278_Assurance_Research_Path.md
> +
might want to include a little table at tghe bottom with a sumarry of all the links shared (for consistency with other projects) like we have here: https://nhsengland.github.io/datascience/our_work/ds218_rap_community_of_practice/ 

see here: https://github.com/nhsengland/datascience/blob/main/docs/our_work/a_and_e_forecasting_tool.md?plain=1 how to code it in

2025-01-07 12:18 UTC, amaiaita commented on docs/our_work/ds278_Assurance_Research_Path.md
looks good overall! just a couple of minor changes, main thing that needs changing ebfore I can approve is the tags and then also it needs adding to the navigation. currently when opening the website with this it appears outside of any navigation, so it needs to be placed in the correct places in this file: https://github.com/nhsengland/datascience/blob/main/mkdocs.yml

2025-01-14 16:26 UTC, benwallace2nhs commented on docs/our_work/ds278_Assurance_Research_Path.md
> +
I think because the links are towards the bottom of the page anyway I won't do this.

2025-01-15 12:28 UTC, amaiaita approved these changes

2025-01-15 12:29 UTC, merged